### ISSUE TITLE
imgpkg copy should be re-runnable for registries that disallow mutating tags

### ISSUE THREAD

**Issue by DennisDenuto** [carvel-dev/imgpkg#199]
**Describe the problem/challenge you have**

Based on the following slack conversation: https://kubernetes.slack.com/archives/CH8KCCKA5/p1626878622031300

There appears to be errors when re-running `imgpkg copy` with the same bundle, targeting a registry that does not allow mutating tags.

Error received:
```
TAG_INVALID: The image tag 'sha256-ABCDEF.image-locations.imgpkg' already exists and cannot be overwritten because the repository is immutable
```

**Describe the solution you'd like**
Ensure re-running `imgpkg copy` with the same input works on registries that dis-allow mutating tags.

**Anything else you would like to add:**
linked thread was using version: v0.14.0

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by gabegorelick** [comment]
> There appears to be errors when re-running imgpkg copy with the same bundle, targeting a registry that does not allow mutating tags.

One (big) caveat: it doesn't appear to be a consistent issue. Much of the time, rerunning `imgpkg copy` works fine. 

It's possible there is some kind of non-determinism going into the image-locations generation, but there doesn't seem to be a good way to grab the `image-locations.yml` that `imgpkg` is attempting to upload to confirm this.

**Comment by DennisDenuto** [comment]
Hi @gabegorelick 

I have spent some time trying to get oci-location to 'mutate' across runs. But I have been unable to do so.

Check out this branch for a e2e test https://github.com/vmware-tanzu/carvel-imgpkg/tree/try-find-oci-location-mutate-exploration

Are you able to provide more information:
- bundle / nested-bundle structure
-- images.yml for each bundle / nested-bundle


In the meanwhile, I have submitted a [PR](https://github.com/vmware-tanzu/carvel-imgpkg/pull/205) in an attempt to prevent saving an oci-location image if it already exists

**Comment by DennisDenuto** [comment]
From the slack convo:

We were provided with the following info https://kubernetes.slack.com/archives/CH8KCCKA5/p1627569740185300?thread_ts=1626878622.031300&cid=CH8KCCKA5:

```
---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
  - image: ghcr.io/external-secrets/kubernetes-external-secrets@sha256:76b1e4948ddd1bac562248bac9fe2149b9b96d1b319fb7cf1c6ad07e9d13e5e1
    isBundle: false
  - image: index.docker.io/fluent/fluent-bit@sha256:8e3fdc011d3ff98502143650dfa3261860b11f1f289dbb3184c630f71236a366
    isBundle: false
  - image: k8s.gcr.io/autoscaling/cluster-autoscaler@sha256:1c19fa17b29db548d0304e9444adf84e8a6f38ee4c0a12d2ecaf262cb10c0e50
    isBundle: false
  - image: k8s.gcr.io/descheduler/descheduler@sha256:61b14f675870d0c2c1b692b99c16662245a23334434662a2820665c8b2557268
    isBundle: false
  - image: k8s.gcr.io/metrics-server/metrics-server@sha256:6c5603956c0aed6b4087a8716afce8eb22f664b13162346ee852b4fab305ca15
    isBundle: false
  - image: k8s.gcr.io/node-problem-detector/node-problem-detector@sha256:072be07890487b187ddf181f9418b4ff92979b70e5acf5a98e39b7dfbfc0ee08
    isBundle: false
  - image: public.ecr.aws/aws-ec2/aws-node-termination-handler@sha256:20e99a648895d2378c1c0656c0464e38f96023012a1aecf6014ffef3be5fa4b7
    isBundle: false
  - image: quay.io/bitnami/sealed-secrets-controller@sha256:cb183c914323dcad01a46e6c879368b2f4706a2c021a9386fb6a6a5e8768fa37
    isBundle: false
kind: ImageLocations
```
