### ISSUE TITLE
Create a Recursive Bundle

### ISSUE THREAD

**Issue by joaopapereira** [carvel-dev/imgpkg#82]
## Use Case

**As A** Software Packager
**I want to** Create a bundle to distribute the multiple applications that are part of a deployment
**So that** Application consumers can retrieve all needed software from a single place

## Prerequirements
The following images exist in the registry

- `my.registry.io/bundle-1@sha256:aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0`
- `my.registry.io/img-1@sha256:bbbbbbbbbbfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0`
- `my.registry.io/img-2@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0`

The `.imgpkg/images.yml` looks like the following
```yaml
apiVersion: imgpkg.carvel.dev/v1alpha1
kind: ImagesLock
images:
- image: my.registry.io/img-1@sha256:bbbbbbbbbbfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
```

### 🟢 Scenario 1: User can create a Recursive Bundle
**Given** the following file exists in `r-bundle/.imgpkg/images.yml`
```yaml
apiVersion: imgpkg.carvel.dev/v1alpha1
kind: ImagesLock
images:
- image: my.registry.io/bundle-1@sha256:aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
```
**When** I run `imgpkg push -b my.registry.io/r-bundle -f r-bundle/ --experimental-recursive-bundle`
**Then** I should see
```
dir: r-bundle/
dir: r-bundle/.imgpkg
file: r-bundle/.imgpkg/images.yml
Pushed 'my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0'
Succeeded
```
**When** I run `imgpkg pull -b my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0  -o /tmp/recursive-bundle`
**Then** I should see
```
Pulling bundle 'my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0'
Extracting layer 'sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0' (1/1)
Locating image lock file images...
One or more images not found in bundle repo; skipping lock file update

Succeeded
```

### 🟢 Scenario 2: User can create a Recursive Bundle with Images
**Given** the following file exists in `r-bundle/.imgpkg/images.yml`
```yaml
apiVersion: imgpkg.carvel.dev/v1alpha1
kind: ImagesLock
images:
- image: my.registry.io/bundle-1@sha256:aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
- image: my.registry.io/img-1@sha256:bbbbbbbbbbfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
```
**When** I run `imgpkg push -b my.registry.io/r-bundle -f r-bundle/ --experimental-recursive-bundle`
**Then** I should see
```
dir: r-bundle/
dir: r-bundle/.imgpkg
file: r-bundle/.imgpkg/images.yml
Pushed 'my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0'
Succeeded
```
**When** I run `imgpkg pull -b my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0  -o /tmp/recursive-bundle`
**Then** I should see
```
Pulling bundle 'my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0'
Extracting layer 'sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0' (1/1)
Locating image lock file images...
One or more images not found in bundle repo; skipping lock file update

Succeeded
```

### 🔴  Scenario 3: Keep behavior without `--experimental-recursive-bundle` flag
**Given** the following file exists in `r-bundle/.imgpkg/images.yml`
```yaml
apiVersion: imgpkg.carvel.dev/v1alpha1
kind: ImagesLock
images:
- image: my.registry.io/bundle-1@sha256:aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
```
**When** I run `imgpkg push -b my.registry.io/r-bundle -f r-bundle/`
**Then** I should see
```
Error: Expected image lock to not contain bundle reference: 'my.registry.io/bundle-1@sha256:aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0'
```

**Notes:**
- The output of `imgpkg pull` will not be changed in this story, a future story will change it to match the proposal
- Add the experimental flag `--experimental-recursive-bundle` to push
