### ISSUE TITLE
Retrieve all Bundles referenced by a Bundle to disk

### ISSUE THREAD

**Issue by joaopapereira** [carvel-dev/imgpkg#83]
## Use Case

**As A** Software Packager
**I want to** Create a bundle to distribute the multiple applications that are part of a deployment
**So that** Application consumers can retrieve all needed software from a single place

## Prerequirements
The following images exist in the registry

- `my.registry.io/bundle-1@sha256:aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0`
  The `.imgpkg/images.yml` looks like the following
  ```yaml
  apiVersion: imgpkg.carvel.dev/v1alpha1
  kind: ImagesLock
  images:
  - image: my.registry.io/img-1@sha256:bbbbbbbbbbfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
  - image: my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
  ```

- `my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0`
  The `.imgpkg/images.yml` looks like the following
  ```yaml
  apiVersion: imgpkg.carvel.dev/v1alpha1
  kind: ImagesLock
  images:
  - image: my.registry.io/img-2@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
  ```

- `my.registry.io/img-1@sha256:bbbbbbbbbbfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0`
- `my.registry.io/img-2@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0`

### 🟢 Scenario 1: User retrieve all the bundles using `-r` flag
**Given** the following file exists in `r-bundle/.imgpkg/images.yml`
```yaml
apiVersion: imgpkg.carvel.dev/v1alpha1
kind: ImagesLock
images:
- image: my.registry.io/bundle-1@sha256:aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
- image: my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
```
**When** I run `imgpkg push -b my.registry.io/r-bundle -f r-bundle/ --experimental-recursive-bundle`
**Then** I should see
```
dir: r-bundle/
dir: r-bundle/.imgpkg
file: r-bundle/.imgpkg/images.yml
Pushed 'my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0'
Succeeded
```
**When** I run `imgpkg pull -r -b my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0  -o /tmp/recursive-bundle`
**Then** I should see
```
Pulling bundle 'my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0'
Bundle Layers
  Extracting layer 'sha256:87bf2c587b3315143cd05df7bd24d4e608ddb59f8c62110fe1b579fb817a2917' (1/1)

Nested bundles
  Pulling Bundle 'my.registry.io/bundle-1@sha256:aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0' (1/2)
  Extracting layer 'sha256:81fc6f37c9774541136e6113d899c215151496f4cf91c89c056783d2feb5ae0d' (1/1)
    Found 1 Bundle packaged

    Pulling Nested Bundle 'my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0' (1/1)
    Extracting layer 'sha256:9abb11371e7e53b5c33da086ea50dabb5d4cdd280be7d489169374b0188feab1' (1/1)

  Pulling Nested Bundle 'my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0' (2/2)
  Skipped, already downloaded

Locating image lock file images...
One or more images not found in bundle repo; skipping lock file update

Succeeded
```
**When** I execute `tree -a /tmp/recursive-bundle`
**Then** I should see
```
/tmp/recursive-bundle
├── .imgpkg
|   ├── bundles
|   │   ├── sha256-ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
|   │   │   ├── .imgpkg
|   │   │   │   ├── bundle.yml
|   │   │   │   └── images.yml
|   │   │   └── config2.yml
|   │   └── sha256-aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
|   │       ├── .imgpkg
|   │       │   ├── bundle.yml
|   │       │   └── images.yml
|   │       └── config1.yml
│   ├── bundle.yml
│   └── images.yml
└── config.yml

7 directories, 9 files
```

### 🟢 Scenario 2: User retrieve all the bundles using `--recursive` flag
__Note:__ same as the above scenario but using the long version of the flag

**Given** the following file exists in `r-bundle/.imgpkg/images.yml`
```yaml
apiVersion: imgpkg.carvel.dev/v1alpha1
kind: ImagesLock
images:
- image: my.registry.io/bundle-1@sha256:aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
- image: my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
```
**When** I run `imgpkg push -b my.registry.io/r-bundle -f r-bundle/ --experimental-recursive-bundle`
**Then** I should see
```
dir: r-bundle/
dir: r-bundle/.imgpkg
file: r-bundle/.imgpkg/images.yml
Pushed 'my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0'
Succeeded
```
**When** I run `imgpkg pull --recursive -b my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0  -o /tmp/recursive-bundle`
**Then** I should see
```
Pulling bundle 'my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0'
Bundle Layers
  Extracting layer 'sha256:87bf2c587b3315143cd05df7bd24d4e608ddb59f8c62110fe1b579fb817a2917' (1/1)

Nested bundles
  Pulling Bundle 'my.registry.io/bundle-1@sha256:aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0' (1/2)
  Extracting layer 'sha256:81fc6f37c9774541136e6113d899c215151496f4cf91c89c056783d2feb5ae0d' (1/1)
    Found 1 Bundle packaged

    Pulling Nested Bundle 'my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0' (1/1)
    Extracting layer 'sha256:9abb11371e7e53b5c33da086ea50dabb5d4cdd280be7d489169374b0188feab1' (1/1)

  Pulling Nested Bundle 'my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0' (2/2)
  Skipped, already downloaded

Locating image lock file images...
One or more images not found in bundle repo; skipping lock file update

Succeeded
```
**When** I execute `tree -a /tmp/recursive-bundle`
**Then** I should see
```
/tmp/recursive-bundle
├── .imgpkg
|   ├── bundles
|   │   ├── sha256-ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
|   │   │   ├── .imgpkg
|   │   │   │   ├── bundle.yml
|   │   │   │   └── images.yml
|   │   │   └── config2.yml
|   │   └── sha256-aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
|   │       ├── .imgpkg
|   │       │   ├── bundle.yml
|   │       │   └── images.yml
|   │       └── config1.yml
│   ├── bundle.yml
│   └── images.yml
└── config.yml

7 directories, 9 files
```

### 🟢 Scenario 3: User retrieve same bundle **without** `-r` flag
__Note:__ There is a change in the output of the pull command

**Given** the following file exists in `r-bundle/.imgpkg/images.yml`
```yaml
apiVersion: imgpkg.carvel.dev/v1alpha1
kind: ImagesLock
images:
- image: my.registry.io/bundle-1@sha256:aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
- image: my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
```
**When** I run `imgpkg push -b my.registry.io/r-bundle -f r-bundle/ --experimental-recursive-bundle`
**Then** I should see
```
dir: r-bundle/
dir: r-bundle/.imgpkg
file: r-bundle/.imgpkg/images.yml
Pushed 'my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0'
Succeeded
```
**When** I run `imgpkg pull -b my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0  -o /tmp/recursive-bundle`
**Then** I should see
```
Pulling bundle 'my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0'
Bundle Layers
  Extracting layer 'sha256:87bf2c587b3315143cd05df7bd24d4e608ddb59f8c62110fe1b579fb817a2917' (1/1)
  
Nested bundles
  Bundle 'my.registry.io/bundle-1@sha256:aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0' (1/2)
  Bundle 'my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0' (2/2)

To retrieve the configuration of all the nested bundles use the command

imgpkg pull --recursive -b my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0  -o /tmp/recursive-bundle

Locating image lock file images...
One or more images not found in bundle repo; skipping lock file update

Succeeded
```

### 🟢 Scenario 4: User retrieve a Bundle only with images with `-r` flag
**Given** the pre requirements exist
**When** I run `imgpkg pull -r -b my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0`
**Then** I should see
```
Pulling bundle 'my.registry.io/r-bundle@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0'
Bundle Layers
  Extracting layer 'sha256:87bf2c587b3315143cd05df7bd24d4e608ddb59f8c62110fe1b579fb817a2917' (1/1)
  
Locating image lock file images...
One or more images not found in bundle repo; skipping lock file update

Succeeded
```
