### ISSUE TITLE
Copy Recursive Bundles from Lock file to tar

### ISSUE THREAD

**Issue by joaopapereira** [carvel-dev/imgpkg#87]
## Use Case

**As A** Software Packager
**I want to** Create a bundle to distribute the multiple applications that are part of a deployment
**So that** Application consumers can retrieve all needed software from a single place

⚠️ This story might be already fully implemented by issue #86. This story is to ensure we have all the requirements needed in our backlog

## Prerequirements
The following images exist in the registry

- `my.registry.io/bundle-1@sha256:aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0`
  The `.imgpkg/images.yml` looks like the following
  ```yaml
  apiVersion: imgpkg.carvel.dev/v1alpha1
  kind: ImagesLock
  images:
  - image: my.registry.io/img-1@sha256:bbbbbbbbbbfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
  - image: my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
  ```

- `my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0`
  The `.imgpkg/images.yml` looks like the following
  ```yaml
  apiVersion: imgpkg.carvel.dev/v1alpha1
  kind: ImagesLock
  images:
  - image: my.registry.io/img-2@sha256:eeeeeeeeeefdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
  ```

- `my.registry.io/img-1@sha256:bbbbbbbbbbfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0`
- `my.registry.io/img-2@sha256:eeeeeeeeeefdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0`

### 🟢 Scenario 1: User copies recursive bundles from a bundle lock file to a tar using `--experimental-recursive-bundle`
**Given** the following file exists in `r-bundle/.imgpkg/images.yml`
```yaml
apiVersion: imgpkg.carvel.dev/v1alpha1
kind: ImagesLock
images:
- image: my.registry.io/bundle-1@sha256:aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
- image: my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
```
**When** I run `imgpkg push -b my.registry.io/r-bundle -f r-bundle/ --experimental-recursive-bundle --lock-output /tmp/bundle.lock`
**Then** I should see
```
dir: r-bundle/
dir: r-bundle/.imgpkg
file: r-bundle/.imgpkg/images.yml
Pushed 'my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0'
Succeeded
```
**When** I run `imgpkg copy --lock /tmp/bundle.lock --to-tar /tmp/r-bundle.tar --experimental-recursive-bundle`
**Then** I should see
```
copy | exporting 5 images...
copy | will export my.registry.io/img-1@sha256:bbbbbbbbbbfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
copy | will export my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
copy | will export my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
copy | will export my.registry.io/bundle-1@sha256:aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
copy | will export my.registry.io/img-2@sha256:eeeeeeeeeefdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
copy | exported 5 images
copy | writing layers...
copy | done: file 'manifest.json' (35.107µs)
copy | done: file 'sha256-81fc6f37c9774541136e6113d899c215151496f4cf91c89c056783d2feb5ae0d.tar.gz' (46.817µs)
copy | done: file 'sha256-9abb11371e7e53b5c33da086ea50dabb5d4cdd280be7d489169374b0188feab1.tar.gz' (99.194µs)
copy | done: file 'sha256-87bf2c587b3315143cd05df7bd24d4e608ddb59f8c62110fe1b579fb817a2917.tar.gz' (119.416µs)
copy | done: file 'sha256-8ece9ac45f2b7228b2ed95e9f407b4f0dc2ac74f93c62ff1156f24c53042ba54.tar.gz' (370.872834ms)
copy | done: file 'sha256-7ekwjlfkjiekserwefwdfwd95e9f407b4f0dc2ac74f93c62ff1156f24c530sdfs43.tar.gz' (130.39ms)
Succeeded
```

### 🟢 Scenario 2: Maintain behavior without `--experimental-recursive-bundle` on simple bundles using a bundle lock file
**Given** I create the file `/tmp/bundle.lock` with the content
```
---
apiVersion: imgpkg.carvel.dev/v1alpha1
bundle:
  image: my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
  tag: latest
kind: BundleLock
```
**When** I run `imgpkg copy --lock /tmp/bundle.lock --to-tar /tmp/bundle-2.tar`
**Then** I should see
```
copy | exporting 2 images...
copy | will export my.registry.io/img-2@sha256:eeeeeeeeeefdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
copy | will export my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
copy | exported 2 images
copy | exported 5 images
copy | writing layers...
copy | done: file 'manifest.json' (35.107µs)
copy | done: file 'sha256-81fc6f37c9774541136e6113d899c215151496f4cf91c89c056783d2feb5ae0d.tar.gz' (46.817µs)
copy | done: file 'sha256-9abb11371e7e53b5c33da086ea50dabb5d4cdd280be7d489169374b0188feab1.tar.gz' (99.194µs)

Succeeded
```

### 🔴 Scenario 3: Fail without `--experimental-recursive-bundle` on recursive bundle bundles using a bundle lock file
**Given** the following file exists in `r-bundle/.imgpkg/images.yml`
```yaml
apiVersion: imgpkg.carvel.dev/v1alpha1
kind: ImagesLock
images:
  - image: my.registry.io/bundle-1@sha256:aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
  - image: my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
```
**When** I run `imgpkg push -b my.registry.io/r-bundle -f r-bundle/ --experimental-recursive-bundle --lock-output /tmp/bundle.lock`
**Then** I should see
```
dir: r-bundle/
dir: r-bundle/.imgpkg
file: r-bundle/.imgpkg/images.yml
Pushed 'my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0'
Succeeded
```
**When** I run `imgpkg copy --lock /tmp/bundle.lock --to-tar /tmp/bundle-2.tar`
**Then** I should see
```
Error: This bundle contains bundles, in order to copy please execute the following command

imgpkg copy -b my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0 --to-tar /tmp/bundle-2.tar --experimental-recursive-bundle
```

### 🔴 Scenario 4: Fails when try to copy bundle using an image lock file
**Given** the following file exists in `/tmp/images.lock.yml`
```yaml
apiVersion: imgpkg.carvel.dev/v1alpha1
kind: ImagesLock
images:
- image: my.registry.io/bundle-1@sha256:aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
- image: my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
```
**When** I run `imgpkg copy --lock /tmp/images.lock.yml --to-tar /tmp/bundle-2.tar --experimental-recursive-bundle`
**Then** I should see
```
Error: Unable to copy bundles using an Images Lock file (hint: Create a bundle with these images)
```

**Notes:**
- Scenario 3 is temporary will be removed when the experimental flag is removed
- Scenario 4 might just be a change in the current error message
