### ISSUE TITLE
Remove experimental recursive bundle flag

### ISSUE THREAD

**Issue by joaopapereira** [carvel-dev/imgpkg#91]
## Use Case

**As A** Software Packager
**I want to** Create a bundle to distribute the multiple applications that are part of a deployment
**So that** Application consumers can retrieve all needed software from a single place

## Prerequirements
The following images exist in the registry

- `my.registry.io/bundle-1@sha256:aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0`
  The `.imgpkg/images.yml` looks like the following
  ```yaml
  apiVersion: imgpkg.carvel.dev/v1alpha1
  kind: ImagesLock
  images:
  - image: my.registry.io/img-1@sha256:bbbbbbbbbbfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
  - image: my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
  ```

- `my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0`
  The `.imgpkg/images.yml` looks like the following
  ```yaml
  apiVersion: imgpkg.carvel.dev/v1alpha1
  kind: ImagesLock
  images:
  - image: my.registry.io/img-2@sha256:eeeeeeeeeefdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
  ```

- `my.registry.io/img-1@sha256:bbbbbbbbbbfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0`
- `my.registry.io/img-2@sha256:eeeeeeeeeefdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0`

### 🟢 Scenario 1: User can push, copy and, pull a bundle of bundles without the flag `--experimental-recursive-bundle`
**Given** the following file exists in `r-bundle/.imgpkg/images.yml`
```yaml
apiVersion: imgpkg.carvel.dev/v1alpha1
kind: ImagesLock
images:
  - image: my.registry.io/bundle-1@sha256:aaaaaaaaaafdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
  - image: my.registry.io/bundle-2@sha256:ddddddddddfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
```
**When** I run `imgpkg push -b my.registry.io/r-bundle -f r-bundle/`
**Then** I run `imgpkg copy -b my.registry.io/r-bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0 --to-repo other.registry.io/bundle`
**And** I run `imgpkg pull -r -b other.registry.io/bundle@sha256:ccccccccccfdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0  -o /tmp/recursive-bundle`
**And** I should see a successfully pulled bundle

**Notes**
- Check to see if other changes are needed or refactorings that can be done
